export const careerLearningCopy = {
  en: {
    index: {
      eyebrow: "Career Learning",
      title: "Study the next useful capability.",
      intro:
        "Reviewed Core Notes connect capability gaps, roadmap milestones, and proof requirements without turning study activity into proficiency.",
      recommendedNow: "Recommended now",
      currentPath: "Current learning path",
      explore: "Explore competencies",
      noProfile: "Create a Career Profile to unlock contextual recommendations.",
      noPersonalizedRecommendation: "Personalized recommendations require a Career Profile.",
      noRecommendation: "No reviewed learning recommendation is available for your current profile.",
      noCurrentPath: "No reviewed modules are mapped to the current roadmap milestone yet.",
      openNote: "Open Core Note",
      continueStudy: "Continue learning",
      prove: "Prove this capability",
      minutes: "min",
    },
    states: {
      "not-started": "Not started",
      "in-progress": "In progress",
      studied: "Studied",
    },
    reasons: {
      "blocking-gap": "Blocking capability gap",
      "current-milestone": "Current roadmap milestone",
      prerequisite: "Required prerequisite",
      "next-role-competency": "Next role competency",
      "studied-not-proved": "Studied — proof still required",
    },
    domains: {
      programming: "Programming",
      frontend: "Frontend",
      backend: "Backend",
      quality: "Quality",
      "engineering-workflow": "Engineering workflow",
    },
    reader: {
      eyebrow: "Core Note",
      objective: "Objective",
      understand: "Understand",
      example: "Example",
      commonMistake: "Common mistake",
      practice: "Practice",
      consolidationCriteria: "Consolidation criteria",
      sources: "Sources",
      noExample: "No reviewed code example is available for this module.",
      markPractice: "Mark practice complete",
      practiceComplete: "Practice complete",
      completeModule: "Mark module studied",
      moduleStudied: "Module studied",
      studied: "Studied",
      studiedTitle: "Content studied",
      proofStillRequired:
        "Studying this content does not prove proficiency. Evidence or an assessment is still required.",
      incompleteCoverage:
        "This Core Note has material still under review. Draft module content is intentionally hidden.",
      notFound: "Core Note not found.",
      reviewed: "Reviewed",
      authority: "Authority",
      lastReviewed: "Last reviewed",
      minutes: "min",
    },
  },
  "pt-BR": {
    index: {
      eyebrow: "Career Learning",
      title: "Estude a próxima capacidade que realmente importa.",
      intro:
        "Core Notes revisadas conectam gaps de capacidade, marcos do roadmap e exigências de comprovação sem transformar atividade de estudo em proficiência.",
      recommendedNow: "Recomendado para você agora",
      currentPath: "Sua trilha atual",
      explore: "Explorar competências",
      noProfile: "Crie um Career Profile para desbloquear recomendações contextuais.",
      noPersonalizedRecommendation: "Recomendações personalizadas exigem um Career Profile.",
      noRecommendation: "Nenhuma recomendação de aprendizado revisada está disponível para seu perfil atual.",
      noCurrentPath: "Ainda não há módulos revisados mapeados ao marco atual do roadmap.",
      openNote: "Abrir Core Note",
      continueStudy: "Continuar aprendizado",
      prove: "Comprovar esta capacidade",
      minutes: "min",
    },
    states: {
      "not-started": "Não iniciado",
      "in-progress": "Em andamento",
      studied: "Estudado",
    },
    reasons: {
      "blocking-gap": "Gap bloqueador de capacidade",
      "current-milestone": "Marco atual do roadmap",
      prerequisite: "Pré-requisito necessário",
      "next-role-competency": "Próxima competência da função",
      "studied-not-proved": "Estudado — comprovação ainda necessária",
    },
    domains: {
      programming: "Programação",
      frontend: "Frontend",
      backend: "Backend",
      quality: "Qualidade",
      "engineering-workflow": "Fluxo de engenharia",
    },
    reader: {
      eyebrow: "Core Note",
      objective: "Objetivo",
      understand: "Entenda",
      example: "Exemplo",
      commonMistake: "Erro comum",
      practice: "Prática",
      consolidationCriteria: "Critérios de consolidação",
      sources: "Fontes",
      noExample: "Nenhum exemplo de código revisado está disponível para este módulo.",
      markPractice: "Marcar prática como concluída",
      practiceComplete: "Prática concluída",
      completeModule: "Marcar módulo como estudado",
      moduleStudied: "Módulo estudado",
      studied: "Estudado",
      studiedTitle: "Conteúdo estudado",
      proofStillRequired:
        "Estudar este conteúdo não comprova proficiência. Ainda é necessária uma evidência ou avaliação.",
      incompleteCoverage:
        "Esta Core Note ainda possui material em revisão. O conteúdo de módulos em rascunho fica intencionalmente oculto.",
      notFound: "Core Note não encontrada.",
      reviewed: "Revisado",
      authority: "Autoridade",
      lastReviewed: "Última revisão",
      minutes: "min",
    },
  },
} as const;
